services:
  shell-app1:
    image: knightsdata/test-monorepo:shell
    command: app1/script.sh
    environment:
      - ENVIRONMENT_VARIABLE=${TEST_ENV_VAR}
    volumes:
      - ${VARIABLE_LOCATION}:/data
    networks:
      - services

networks:
  services:
    external: true
