name: Configure Build Context

on:
  workflow_call:
    inputs:
      src_type:
        required: true
        type: string
      
jobs: 
  configure-production:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            it-scripts-${{ inputs.src_type }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}

  configure-development:
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            it-scripts-${{ inputs.src_type }}
          tags: |
            type=ref,event=branch
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
 
  start-build:
     uses: ./.github/workflows/__build-image.yml
     with:
       src_type: ${{ inputs.src_type }}
       env_type: development
       meta_tags: ${{ needs.jobs.configure-development.outputs.tags }}
       meta_labels: ${{ needs.jobs.configure-development.outputs.labels }}
