name: Run Image Build

on:
  workflow_call:
    inputs:
      src_type:
        required: true
        type: string
      env_type:
        required: true
        type: string
      meta_tags:
        required: true
        type: string
      meta_labels:
        required: true
        type: string
      
jobs: 
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Check out the repo
        uses: actions/checkout@v4      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: src
          target: ${{ github.event.inputs.src_type }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.event.inputs.meta_tags }}
          labels: ${{ github.event.inputs.meta_labels }}

      - run: echo "🍏 ${{ github.event.inputs.env_type }} ${{ github.event.inputs.src_type }} build is a ${{ job.status }}."
    
