name: Configure Build Context

on:
  workflow_call:
    inputs:
      src_type:
        required: true
        type: string
      
jobs: 
  configure-environment:
    runs-on: ubuntu-latest
    outputs:
      env_type: ${{ steps.detect_vars.outputs.env_type }}
      meta_tags: ${{ steps.detect_vars.outputs.meta_tags }}
      meta_labels: ${{ steps.detect_vars.outputs.meta_labels }}
    steps:
      - name: Production Docker meta
        id: prd_meta
        if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
        uses: docker/metadata-action@v5
        with:
          images: |
            it-scripts-${{ inputs.src_type }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha

      - name: Development Docker meta
        id: dev_meta
        if: github.ref_name == 'develop'
        uses: docker/metadata-action@v5
        with:
          images: |
            it-scripts-${{ inputs.src_type }}
          tags: |
            type=ref,event=branch

      - run: echo "${{ steps.dev_meta.outputs.tags }}"
      - name: Use development unless production detected
        id: detected_vars
        run: |
          if [ -n "${{ steps.prd_meta.outputs.tags }}" ]; then
            echo "Setting Production Variables"
            echo "env_type=production" >> $GITHUB_OUTPUT
            echo "meta_tags=${{ steps.prd_meta.outputs.tags }}" >> $GITHUB_OUTPUT
            echo "meta_labels=${{ steps.prd_meta.outputs.labels }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ steps.dev_meta.outputs.tags }}" ]; then
            echo "Setting Development Variables"
            echo "env_type=development" >> $GITHUB_OUTPUT
            echo "meta_tags=${{ steps.dev_meta.outputs.tags }}" >> $GITHUB_OUTPUT
            echo "meta_labels=${{ steps.dev_meta.outputs.labels }}" >> $GITHUB_OUTPUT
          else
            echo "No image tags for build environment detected"
            exit 1
          fi

  start-build:
    needs: [ configure-environment ] 
    uses: ./.github/workflows/_build-image.yml
    with:
      src_type: ${{ inputs.src_type }}
      env_type: ${{ needs.jobs.configure-environment.outputs.env_type }}
      meta_tags: ${{ needs.jobs.configure-environment.outputs.meta_tags }}
      meta_labels: ${{ needs.jobs.configure-environment.outputs.meta_labels }}
