name: Configure Build Context

on:
  workflow_call:
    inputs:
      src_type:
        required: true
        type: string
      
jobs: 
  configure-production:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            it-scripts-${{ inputs.src_type }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}

  configure-development:
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            it-scripts-${{ inputs.src_type }}
          tags: |
            type=ref,event=branch
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}

  set-variables:
    runs-on: ubuntu-latest
    needs: [configure-production, configure-development]
    outputs:
      env_type: ${{ needs.steps.detected_vars.outputs.env_type }} 
      meta_tags: ${{ needs.steps.detected_vars.outputs.meta_tags }}
      meta_labels: ${{ needs.steps.detected_vars.outputs.meta_labels }}
    steps:
      - name: Use development unless production detected
        id: detected_vars
        run: |
          if [ -n "${{ needs.jobs.configure-production.outputs.tags }}" ]; then
            echo "::set-output name=env_type::production"
            echo "::set-output name=meta_tags::${{ needs.jobs.configure-production.outputs.tags }}"
            echo "::set-output name=meta_labels::${{ needs.jobs.configure-production.outputs.labels }}"
          elif [ -n "${{ needs.jobs.configure-development.outputs.tags }}" ]; then
            echo "::set-output name=env_type::development"
            echo "::set-output name=meta_tags::${{ needs.jobs.configure-development.outputs.tags }}"
            echo "::set-output name=meta_labels::${{ needs.jobs.configure-development.outputs.labels }}"
          else
            echo "No image tags for build environment detected"
            exit 1
          fi

  start-build:
     uses: ./.github/workflows/_build-image.yml
     with:
       src_type: ${{ inputs.src_type }}
       env_type: ${{ needs.jobs.set-variables.outputs.env_type }}
       meta_tags: ${{ needs.jobs.set-variables.outputs.meta_tags }}
       meta_labels: ${{ needs.jobs.set-variables.outputs.meta_labels }}
