name: Build Python Image

run-name: ${{ github.actor }} is building the python image

on:
  push:
    branches:
      - develop
    paths:
      - 'python/**'
      - Dockerfile
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'python/**'
      - Dockerfile

env: 
  SRC_TYPE: python

jobs:
  build-production:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building ${SRC_TYPE} production image on merge to main"

  build-develop:
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building ${SRC_TYPE} development image on push to develop branch"


      #jobs:
      #  build-image:
      #    runs-on: ubuntu-latest
      #    steps:
      #      -
      #        name: Set up QEMU
      #        uses: docker/setup-qemu-action@v3
      #      -
      #        name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v3
      #      - 
      #        name: Check out the repo
      #        uses: actions/checkout@v4      
      #      -
      #        name: Login to Docker Hub
      #        uses: docker/login-action@v3
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #      -
      #        name: Build and push
      #        uses: docker/build-push-action@v6
      #        with:
      #          push: true
      #          context: .
      #          target: python
      #          tags: knightsdata/test-monorepo:python
      #
      #      - run: echo "🍏 This job's status is ${{ job.status }}."
