name: Build Python Image

run-name: ${{ github.actor }} is building the python image

on:
  push:
    branches:
      - develop
    paths:
      - 'python/**'
      - Dockerfile
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'python/**'
      - Dockerfile

env: 
  SRC_TYPE: python

jobs:
  determine-build-context:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v4      
      - 
        name: Build Context
        uses: ./.github/workflows/__configure-context.yml
        with: 
          src_type: ${{ env.SRC_TYPE }}
