name: Build Python Image

run-name: ${{ github.actor }} is building the python image

on:
  push:
    branches:
      - develop
    paths:
      - 'python/**'
      - Dockerfile
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'python/**'
      - Dockerfile

jobs:
  determine-build-context:
    uses: ./.github/workflows/__configure-context.yml
    with:
      src_type: python
