name: Call a reusable workflow and use its outputs

on:
  push:

jobs:
  job1:
    uses: ./.github/workflows/test2.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}

